apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ingress-monitor:operator
rules:
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ingress-monitor:operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-monitor:operator
subjects:
  - name: ingress-monitor
    namespace: ingress-monitor
    kind: ServiceAccount

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-monitor
  namespace: ingress-monitor

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingress-monitor-operator
  namespace: ingress-monitor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ingress-monitor-operator
    spec:
      serviceAccountName: ingress-monitor
      containers:
        - name: ingress-monitor-operator
          image: jelmersnoeck/ingress-monitor:latest
          imagePullPolicy: IfNotPresent
          args:
          - operator
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            requests:
              cpu: 10m
              memory: 10Mi
